AWSTemplateFormatVersion: "2010-09-09"
Description: Skill Table
Parameters:
  SkillSessionTableName:
    Description: Skill Table
    Type: 'String'
Resources:
  SkillSessionTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Delete
    Properties:
      AttributeDefinitions:
        -
          AttributeName: userId
          AttributeType: S
      KeySchema:
        -
          AttributeName: userId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: !Ref SkillSessionTableName
