service: skill-sample-nodejs-hello-world

plugins:
  - serverless-webpack
  - serverless-mocha-plugin

custom: ${file(./.env.${opt:config, 'dev'}.yml)}

provider:
  name: aws
  runtime: nodejs6.10
  stackTags:
    APPLICATION: skill-sample-nodejs-hello-world
    TYPE: skill

  stage: ${opt:stage, 'dev'}
  region: ${self:custom.AWS_REGION}
  profile: ${self:custom.AWS_PROFILE}
  memorySize: ${self:custom.AWS_MEMORY_SIZE, '256'}
  cfLogs: true

functions:
  skill:
    handler: index.handler
    description: Alexa hello world skill
    events:
      - alexaSkill
    environment:
      DEBUG: ${self:custom.DEBUG}
      NODE_ENV: ${self:custom.NODE_ENV, 'dev'}
      SKILL_FILE_STORAGE: ${self:custom.SKILL_FILE_STORAGE}
      SKILL_APP_ID: ${self:custom.SKILL_APP_ID}

resources:
  Resources:
    SkillLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
