'use strict';

// tests for skill
// Generated by serverless-mocha-plugin

const INTENT_HELLO = require('./service-requests/hello.json');
const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('skill', '/index.js', 'handler');

describe('skill', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    return wrapped.run(INTENT_HELLO).then((response) => {
      expect(response.response.outputSpeech.ssml).to.be.equal('<speak> Hello World! </speak>');
      expect(response.response.card.content).to.be.equal('hello world');
      expect(response.response.card.title).to.be.equal('hello world');
    });
  });
});
